import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const appStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF8F0',
  },
  section: {
    backgroundColor: '#fff',
    margin: 16,
    padding: 20,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2C3E50',
    marginBottom: 8,
    textAlign: 'center',
  },
  sectionSubtitle: {
    fontSize: 16,
    color: '#7F8C8D',
    textAlign: 'center',
    marginBottom: 16,
  },
  heroSection: {
    alignItems: 'center',
    paddingVertical: 30,
    paddingHorizontal: 20,
    backgroundColor: '#FF6B35',
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 12,
  },
  heroImage: {
    width: width - 64,
    height: 200,
    borderRadius: 12,
    marginBottom: 20,
  },
  heroTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    marginBottom: 8,
  },
  heroSubtitle: {
    fontSize: 18,
    color: '#fff',
    textAlign: 'center',
    opacity: 0.9,
  },
  userInfoSection: {
    alignItems: 'center',
  },
  nameInput: {
    borderWidth: 2,
    borderColor: '#FF6B35',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: '#fff',
    width: '100%',
    textAlign: 'center',
  },
  dayGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  dayButton: {
    width: '48%',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#E8E8E8',
    backgroundColor: '#fff',
    marginBottom: 12,
    alignItems: 'center',
  },
  dayButtonSelected: {
    backgroundColor: '#8FBC8F',
    borderColor: '#8FBC8F',
  },
  dayButtonText: {
    fontSize: 16,
    color: '#2C3E50',
    fontWeight: '600',
  },
  dayButtonTextSelected: {
    color: '#fff',
  },
  generateSection: {
    alignItems: 'center',
    marginVertical: 20,
  },
  generateButton: {
    backgroundColor: '#FF6B35',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 25,
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  disabledButton: {
    opacity: 0.6,
  },
  generateButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  mealPlanSection: {
    marginTop: 20,
  },
  mealCard: {
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    overflow: 'hidden',
  },
  mealImageContainer: {
    position: 'relative',
  },
  mealImage: {
    width: '100%',
    height: 200,
  },
  dayBadge: {
    position: 'absolute',
    top: 12,
    left: 12,
    backgroundColor: '#FF6B35',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  dayBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  mealCardContent: {
    padding: 16,
  },
  mealTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2C3E50',
    marginBottom: 8,
  },
  mealMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  mealCategory: {
    fontSize: 14,
    color: '#8FBC8F',
    fontWeight: '600',
  },
  mealArea: {
    fontSize: 14,
    color: '#7F8C8D',
  },
  mealDescription: {
    fontSize: 14,
    color: '#7F8C8D',
    lineHeight: 20,
  },
  shoppingListContainer: {
    maxHeight: 300,
  },
  ingredientItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#F8F9FA',
    marginBottom: 6,
    borderRadius: 8,
  },
  ingredientName: {
    fontSize: 16,
    color: '#2C3E50',
    flex: 1,
  },
  ingredientMeasure: {
    fontSize: 14,
    color: '#7F8C8D',
    fontWeight: '600',
  },
  instructionsContainer: {
    maxHeight: 400,
  },
  instructionCard: {
    backgroundColor: '#F8F9FA',
    padding: 16,
    borderRadius: 8,
    marginBottom: 16,
  },
  instructionMealTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FF6B35',
    marginBottom: 8,
  },
  instructionText: {
    fontSize: 14,
    color: '#2C3E50',
    lineHeight: 20,
  },
  footer: {
    backgroundColor: '#2C3E50',
    padding: 20,
    alignItems: 'center',
    marginTop: 30,
  },
  footerText: {
    color: '#fff',
    fontSize: 14,
    marginBottom: 4,
  },
  apiCredit: {
    color: '#8FBC8F',
    fontSize: 12,
  },
  // Dietary Filters Styles
  filterInputContainer: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  filterInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#E8E8E8',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    marginRight: 8,
  },
  addFilterButton: {
    backgroundColor: '#FF6B35',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    justifyContent: 'center',
  },
  addFilterText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  commonFiltersTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2C3E50',
    marginBottom: 8,
  },
  commonFiltersScroll: {
    marginBottom: 16,
  },
  commonFilterChip: {
    backgroundColor: '#F8F9FA',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#E8E8E8',
  },
  commonFilterChipActive: {
    backgroundColor: '#8FBC8F',
    borderColor: '#8FBC8F',
  },
  commonFilterText: {
    fontSize: 14,
    color: '#2C3E50',
  },
  commonFilterTextActive: {
    color: '#fff',
  },
  activeFiltersContainer: {
    marginTop: 16,
  },
  activeFiltersTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2C3E50',
    marginBottom: 8,
  },
  activeFiltersWrapper: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  activeFilterChip: {
    backgroundColor: '#FF6B35',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    marginRight: 8,
    marginBottom: 8,
  },
  activeFilterText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },

  // Print Button Styles
  printButton: {
    backgroundColor: '#8FBC8F',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 20,
    marginTop: 12,
    shadowColor: '#8FBC8F',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  printButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});